### PR TITLE
Update docker-compose-cpu.yaml

### PR DESCRIPTION
**Pull request by avisil**
Commented nvidia runtime out as it throws an error while compiling in `no gpu` mode.

### CODE REVIEW

**Review by kpfadnis — CHANGES_REQUESTED** [review]
@avisil Please remove it completely as it will not be necessary.

**Comment by avisil** [comment]
@kpfadnis : my bad - done.

**Comment by kpfadnis** [comment]
Fixes #11

**Review by kpfadnis — APPROVED** [review]
LGTM.

**Pull request merged**
